App_Auth/urls.py
from django.urls import path
from App_Auth.views import *

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', signup , name="signup"),
    path('login/', login_page , name="login"),
    path('logout/', logout_page , name="logout"),
    path('change-profile/', change_profile , name="change_profile"),
]

App_Seller/urls.py
from django.urls import path
from App_Seller.views import *

app_name = 'App_Seller'

urlpatterns = [
    path('create-seller/', create_seller , name="create_seller"),
    path('seller-info/', fill_seller_info , name="fill_seller_info"),
    path('seller-dashboard/', seller_dashboard , name="seller_dashboard"),
    path('create-product/', create_product , name="create_product"),
    path('products/', seller_products , name="seller_products"),
    path('product-details/<pk>/', product_details , name="product_details"),
    path('edit-product/<pk>/', edit_product , name="edit_product"),
    path('delete_product/<pk>/', delete_product , name="delete_product"),
    path('create-coupon/', create_coupon , name="create_coupon"),
    path('coupons/', coupons , name="coupons"),
    path('update-coupon/<pk>/', update_coupon , name="update_coupon"),
    path('order/', order_for_seller , name="order_for_seller"),
    path('sent/<pk>/', sent , name="sent"),
    path('category-create/', create_category , name="create_category"),
    path('category/', all_category , name="all_category"),
    path('update-catgory/<pk>/', update_catgory , name="update_catgory"),
]

Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Auth.urls')),
    path('', include('App_Shop.urls')),
    path('orders/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('seller/', include('App_Seller.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Seller/models.py
from django.db import models
from App_Auth.models import User
from App_Order.models import Order
import datetime

# Create your models here.
    
class SellerProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='seller')
    shop_name = models.CharField(max_length=50)
    shop_address = models.CharField(max_length=264)
    shop_category = models.CharField(max_length=50)
    seller_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.shop_name
    
    def is_fully_filled(self):
        fields_names = [f.name for f in self._meta.get_fields()]
        for field_name in fields_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True


class Coupon(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='coupon')
    code = models.CharField(max_length=100)
    discount = models.IntegerField()
    active = models.BooleanField(default=True)
    start_date = models.DateTimeField(default=datetime.datetime.now())
    expiry_date = models.DateTimeField()
    
    def __str__(self):
        return self.code



class Order_seller(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    sent_from_seller = models.BooleanField(default=False)
    

App_Seller/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from App_Seller.models import *
from App_Shop.models import *


        
class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields = ('email', 'password1', 'password2')
    

class SellerProfileForm(ModelForm):
    class Meta:
        model = SellerProfile
        exclude = ('user',)
        
        
class Create_Product_Form(ModelForm):
    class Meta:
        model = Product
        exclude = ('created_by',)
        
        
        
class Create_Coupon_From(ModelForm):
    class Meta:
        model = Coupon
        exclude = ('seller',)
        labels = {
            'discount': 'Discount percentage',
        }
        widgets = {
            'discount': forms.TextInput(attrs={'placeholder': '10'}),
            'start_date': forms.TextInput(attrs={'type': 'datetime-local'}),
            'expiry_date': forms.TextInput(attrs={'type': 'datetime-local'}),
        }
        
        
        
class Create_Category_Form(ModelForm):
    class Meta:
        model = Category
        fields = ('title',)

App_Seller/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.contrib import messages

from App_Seller.forms import *
from App_Order.models import *
# Create your views here.

#seller check

def create_seller(request):
    form = SignupForm()
    seller = True
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.role = 'seller'
            data.save()
            messages.success(request,"Seller Created Successfully!")
            return HttpResponseRedirect(reverse('App_Auth:login'))
    return render(request, 'App_Seller/signup.html', context={'form': form, 'seller': seller})


@login_required
def fill_seller_info(request):
    edit = False
    if (request.user.role != 'seller'):
        messages.warning(request, "Only seller can access this page.")
        return HttpResponseRedirect(reverse('App_Shop:home'))
    if not request.user.seller.exists():
        form = SellerProfileForm()
        if request.method == 'POST':
            form = SellerProfileForm(request.POST)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = request.user
                data.save()
                messages.success(request,"Seller Info Created Successfully!")
                try:
                    if request.GET['next']:
                        return redirect(request.GET['next'])
                except Exception as e:
                    return redirect('App_Shop:home')
    else:
        edit = True
        seller = SellerProfile.objects.get(user=request.user)
        form = SellerProfileForm(instance=seller)
        print(seller)
        if request.method == 'POST':
            form = SellerProfileForm(request.POST, instance=seller)
            if form.is_valid():
                data = form.save(commit=False)
                data.user = request.user
                data.save()
                messages.success(request,"Seller Info Updated Successfully!")
                try:
                    if request.GET['next']:
                        return redirect(request.GET['next'])
                except Exception as e:
                    return redirect('App_Shop:home')
    return render(request, 'App_Seller/create_seller.html', context={'form': form, "edit": edit})


@login_required
def seller_dashboard(request):
    if (request.user.role!='seller'):
        messages.warning(request, "Only seller can access this page.")
        return HttpResponseRedirect(reverse('App_Shop:home'))
    if not request.user.profile.is_fully_filled():
        messages.warning(request,"Complete profile details first!")
        first = reverse("App_Auth:change_profile")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    seller_exists = SellerProfile.objects.filter(user=request.user)
    if not seller_exists:
        messages.warning(request,"Complete seller details first!")
        first = reverse("App_Seller:fill_seller_info")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    return render(request, 'App_Seller/dashboard.html')


@login_required
def create_product(request):
    if (request.user.role!='seller'):
        messages.warning(request, "Only seller can access this page.")
        return HttpResponseRedirect(reverse('App_Shop:home'))
    if not request.user.profile.is_fully_filled():
        messages.warning(request,"Complete profile details first!")
        first = reverse("App_Auth:change_profile")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    seller_exists = SellerProfile.objects.filter(user=request.user)
    if not seller_exists:
        messages.warning(request,"Complete seller details first!")
        first = reverse("App_Seller:fill_seller_info")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    form = Create_Product_Form()
    if (request.method == 'POST'):
        form = Create_Product_Form(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.created_by = request.user
            data.save()
            messages.success(request,"Product Created Successfully!")
            return HttpResponseRedirect(reverse('App_Seller:seller_products'))
    return render(request, 'App_Seller/create_product.html', context={'form': form})


@login_required
def seller_products(request):
    if (request.user.role!='seller'):
        messages.warning(request, "Only seller can access this page.")
        return HttpResponseRedirect(reverse('App_Shop:home'))
    if not request.user.profile.is_fully_filled():
        messages.warning(request,"Complete profile details first!")
        first = reverse("App_Auth:change_profile")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    seller_exists = SellerProfile.objects.filter(user=request.user)
    if not seller_exists:
        messages.warning(request,"Complete seller details first!")
        first = reverse("App_Seller:fill_seller_info")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    products = Product.objects.filter(created_by=request.user)
    return render(request, 'App_Seller/products.html', context={'products': products})

@login_required
def product_details(request, pk):
    if (request.user.role!='seller'):
        messages.warning(request, "Only seller can access this page.")
        return HttpResponseRedirect(reverse('App_Shop:home'))
    if not request.user.profile.is_fully_filled():
        messages.warning(request,"Complete profile details first!")
        first = reverse("App_Auth:change_profile")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    seller_exists = SellerProfile.objects.filter(user=request.user)
    if not seller_exists:
        messages.warning(request,"Complete seller details first!")
        first = reverse("App_Seller:fill_seller_info")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    product = Product.objects.filter(pk=pk, created_by=request.user)
    if not product.exists():
        messages.warning(request,"Product not found")
        return redirect("App_Seller:seller_products")
    return render(request, 'App_Seller/product_detail.html', context={'product': list(product)[0]})


@login_required
def edit_product(request, pk):
    if (request.user.role!='seller'):
        messages.warning(request, "Only seller can access this page.")
        return HttpResponseRedirect(reverse('App_Shop:home'))
    if not request.user.profile.is_fully_filled():
        messages.warning(request,"Complete profile details first!")
        first = reverse("App_Auth:change_profile")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    seller_exists = SellerProfile.objects.filter(user=request.user)
    if not seller_exists:
        messages.warning(request,"Complete seller details first!")
        first = reverse("App_Seller:fill_seller_info")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    edit = True
    product = Product.objects.filter(pk=pk, created_by=request.user)
    if not product.exists():
        messages.warning(request,"Product not found")
        return redirect("App_Seller:seller_products")
    product = list(product)[0]
    form = Create_Product_Form(instance=product)
    if (request.method == 'POST'):
        form = Create_Product_Form(request.POST, request.FILES, instance=product)
        if form.is_valid():
            data = form.save()
            data.save()
            messages.success(request,"Product Updated Successfully!")
            return HttpResponseRedirect(reverse('App_Seller:product_details', kwargs={'pk': pk}))
    return render(request, 'App_Seller/create_product.html', context={'form': form, "edit":edit})


@login_required
def delete_product(request, pk):
    if (request.user.role!='seller'):
        messages.warning(request, "Only seller can access this page.")
        return HttpResponseRedirect(reverse('App_Shop:home'))
    if not request.user.profile.is_fully_filled():
        messages.warning(request,"Complete profile details first!")
        first = reverse("App_Auth:change_profile")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    seller_exists = SellerProfile.objects.filter(user=request.user)
    if not seller_exists:
        messages.warning(request,"Complete seller details first!")
        first = reverse("App_Seller:fill_seller_info")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    product = Product.objects.filter(pk=pk, created_by=request.user)
    if not product.exists():
        messages.warning(request,"Access denied")
        return redirect("App_Seller:seller_products")
    product = list(product)[0]
    product.delete()
    messages.success(request,"Product Deleted Successfully!")
    return HttpResponseRedirect(reverse('App_Seller:seller_products'))


@login_required
def create_coupon(request):
    if (request.user.role!='seller'):
        messages.warning(request, "Only seller can access this page.")
        return HttpResponseRedirect(reverse('App_Shop:home'))
    if not request.user.profile.is_fully_filled():
        messages.warning(request,"Complete profile details first!")
        first = reverse("App_Auth:change_profile")

templates/App_Seller/category.html
{% extends "App_Seller/dashboard.html" %}
{%block title_block%}Categories{%endblock%}
{% block dash_block %}
<div class='dash-page'>
    {%if category|length == 0%}
    <h4>No Categories</h4>
    {%else%}
    <h2 style="text-align: center">Categories</h2>
    {%endif%}
    <div class="dash-section">
    {% for cate in category %}
    <div class="category">
        <span>Category: {{cate.title}}</span>
        <a class='btn btn-warning' href="{%url 'App_Seller:update_catgory' pk=cate.pk%}">Edit</a>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

templates/App_Seller/coupons.html
{% extends "App_Seller/dashboard.html" %}
{%block title_block%}Coupons{%endblock%}
{% block dash_block %}
<div class="dash-page">
  {%if coupons|length == 0%}
  <h4>No Coupons</h4>
  {%else%}
  <h2 style="text-align: center">My Coupons</h2>
  {%endif%}
  <div class="dash-section">
    {% for coupon in coupons %}
    <div class="coupon">
        <h4>Code: {{coupon.code}}</h4>
        <h4>Discount: {{coupon.discount}}</h4>
        <h4>Active: <span class="{%if coupon.active%}text-success{%else%}text-warning{%endif%}">{{coupon.active}}</span></h4>
        <h4>Starting Date: {{coupon.start_date}}</h4>
        <h4>Expairy Date: {{coupon.expiry_date}}</h4>
        <a class='btn btn-warning' href="{%url 'App_Seller:update_coupon' pk=coupon.pk%}">Edit</a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/App_Seller/create_category.html
{% extends "App_Seller/dashboard.html" %} 
{%load crispy_forms_tags%}
{%block title_block%}
    {%if edit%}
    Update Category
    {%else%}
    Create Category
    {%endif%}
{%endblock%}
{% block dash_block %}
<div class="form">
    {%if edit%}
    <h2>Update Category</h2>
    {%else%}
    <h2>Create Category</h2>
    {%endif%}
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button class="btn btn-success w-100" type="submit">
            {%if edit%}
            Update
            {%else%}
            Create
            {%endif%}
        </button>
    </form>
</div>
{%endblock%}

templates/App_Seller/create_coupon.html
{% extends "App_Seller/dashboard.html" %} 
{%load crispy_forms_tags%}
{%block title_block%}
    {%if edit%}
    Update Coupon
    {%else%}
    Create Coupon
    {%endif%}
{%endblock%}
{% block dash_block %}
<div class="form">
    {%if edit%}
    <h2>Update Coupon</h2>
    {%else%}
    <h2>Create Coupon</h2>
    {%endif%}
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button class="btn btn-success w-100" type="submit">
            {%if edit%}
            Update
            {%else%}
            Create
            {%endif%}
        </button>
    </form>
</div>
{%endblock%}

templates/App_Seller/create_product.html
{% extends "App_Seller/dashboard.html" %}
{%load crispy_forms_tags%}
{%block title_block%}
{%if edit%}
    Update product
    {%else%}
    Create product
    {%endif%}
{%endblock%}
{% block dash_block %}
<div class="form">
    {%if edit%}
    <h2>Update product</h2>
    {%else%}
    <h2>Create a product for your shop</h2>
    {%endif%}
    <form method="POST" enctype="multipart/form-data">
        {{form|crispy}}
        {% csrf_token %}
        <button class="btn btn-success w-100" type="submit">
            {%if edit%}
            Update
            {%else%}
            Create
            {%endif%}
        </button>
    </form>
</div>
{%endblock%}

templates/App_Seller/create_seller.html
{% extends "base.html" %}

{%load crispy_forms_tags%}
{%block title_block%}
    {%if edit%}
    Update seller info
    {%else%}
    Create seller info
    {%endif%}
{%endblock%}


{% block body_block %}
<div class="form">
    {%if edit%}
    <h2>Update Seller Information</h2>
    {%else%}
    <h2>Create Seller Information</h2>
    {%endif%}
    
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button class="btn btn-success w-100" type="submit">
            {%if edit%}
            Update
            {%else%}
            Create
            {%endif%}
        </button>
    </form>
</div>
{%endblock%}

templates/App_Seller/dashboard.html
{% extends "base.html" %}
{%load crispy_forms_tags%}
{%block title_block%}Dashboard{%endblock%}
{%block body_block%}
<div class="dashboard">
    <h2 class="text-center">Seller Dashboard</h2>
    <div class="main-content">
        {%block dash_block%}
            <div class="dash-links">
                <a class="dash-circle" href="{%url 'App_Seller:create_category'%}"><i class="fa-solid fa-plus fa-2x"></i>Category</a>
                <a class="dash-circle" href="{%url 'App_Seller:create_product'%}"><i class="fa-solid fa-plus fa-2x"></i>Product</a>
                <a class="dash-circle" href="{%url 'App_Seller:create_coupon'%}"><i class="fa-solid fa-plus fa-2x"></i> Coupon</a>
                <a class="dash-circle" href="{%url 'App_Seller:seller_products'%}">My Products</a>
                <a class="dash-circle" href="{%url 'App_Seller:order_for_seller'%}">My Orders</a>
                <a class="dash-circle" href="{%url 'App_Seller:coupons'%}">My Coupons</a>
                <a class="dash-circle" href="{%url 'App_Seller:all_category'%}">Categories</a>
                <a class="dash-circle" href="{%url 'App_Seller:fill_seller_info'%}">Edit Seller Info</a>
            </div>
        {%endblock%}
    </div>
 </div>
{%endblock%}

templates/App_Seller/order.html
{% extends "App_Seller/dashboard.html" %}
{%load crispy_forms_tags%}
{%block title_block%}My Orders{%endblock%}
{%block dash_block%}
<div class="dash-page">
    {%if order|length == 0%}
    <h4>No Orders</h4>
    {%else%}
    <h2 style="text-align: center">My Orders</h2>
    {%endif%}
    <div class="dash-section">
        {%for order in order%}
        <div class='order-seller'>
            <h3>Sent from seller: {{order.order_item.sent_from_seller}}</h3>
            {%for product in order.seller_order%}
                <p>
                    <a href="{%url 'App_Seller:product_details' pk=product.product.pk%}">{{product.product}}</a> X {{product.quantity}}
                </p>
                {%endfor%}
                {%if order.order_item.sent_from_seller%}
                <a class="btn btn-danger" href="{%url 'App_Seller:sent' pk=order.order_item.pk%}">
                    Not Sent
                </a>
                    {%else%}
                <a class="btn btn-info" href="{%url 'App_Seller:sent' pk=order.order_item.pk%}">
                    Sent
                </a>
            {%endif%}
        </div>
    {%endfor%}
    </div>
 </div>
{%endblock%}

templates/App_Seller/product_detail.html
{% extends "App_Seller/dashboard.html" %}
{% block style_block %}
    .details-page{
         display: flex;
         justify-content: space-around;
         align-items: center;
         padding: 10px;
         width: 100%;
 
    }
    .detail-image{
        width: 40%;
        align-self: flex-start;
        box-shadow: 0 0 2px black;
    }
    .desc{
        font-size: 22px;
    }
    .product-details{
        width: 60%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
        background-color: #f1f1f1;
        box-shadow: 0 0 2px black;
        margin-left: 10px;
        align-self: flex-start;
    }

    @media (max-width: 768px) {
        .details-page{
            flex-direction: column;
       }
       .detail-image{
           width: 100%;
           margin-bottom: 20px;
       }
       .product-details{
           width: 100%;
           margin-left: 0px;
       }
    }
{% endblock %}
{% block title_block %}{{product.name}}{% endblock %}

{% block dash_block %}
<div class="dash-page">
  <div>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">Delete Product</button>
    <a class="btn btn-warning" href="{%url 'App_Seller:edit_product' pk=product.pk%}">Edit Product</a>
  </div>
  <div class="details-page">
    <img class="detail-image" src="/static/{{product.mainimage}}" />
    <div class="product-details">
        <h4>{{ product.name}}</h4>
        <h4>Price: <span class="price">{{ product.price|floatformat:2 }}&#2547;</span> <span class="old-price">{{product.old_price|floatformat:2}}&#2547;</span></h4>
        <u class="desc">Description</u>
        <div style="align-self: flex-start;"> {{ product.description|linebreaks}}</div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure to delete this product?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <a class="btn btn-danger" href="{%url 'App_Seller:delete_product' pk=product.pk%}">Delete</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/App_Seller/products.html
{% extends "App_Seller/dashboard.html" %} 
{%block title_block%}My Products{%endblock%}
{% block dash_block %}
<div class="products-page">
  {%if products|length == 0%}
  <h4>No Products</h4>
  {%else%}
  <h2 style="text-align: center">My Products</h2>
  {%endif%}
  <div class="products">
    {% for product in products %}
    <div class="product-card">
      <img
        class="product-card-image"
        src="/static/{{ product.mainimage }}"
        alt="{{ product.name }}"
      />
      <div class="product-card-body">
        <h4>
          <a
            class="link-title"
            href="{%url 'App_Seller:product_details' pk=product.pk%}"
            >{{ product.name|slice:"20" }}...</a
          >
        </h4>
        <p>
          Price:
          <span class="price">{{ product.price|floatformat:2 }}&#2547;</span>
          <span class="old-price"
            >{{product.old_price|floatformat:2}}&#2547;</span
          >
        </p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/App_Seller/signup.html
{% extends "base.html" %}
{%load crispy_forms_tags%}
{%block title_block%}Seller account create{%endblock%}
{%block body_block%}
<div class="form">
    <h2>Create Seller Account</h2>
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button class="btn btn-success w-100" type="submit">Sign Up</button>
    </form>
    <p class="suggession">Already have an account?<a href="{% url 'App_Auth:login' %}" class="btn btn-info btn-sm">Login</a></p>
</div>
{%endblock%}