App_Auth/urls.py
from django.urls import path
from App_Auth.views import *

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', signup , name="signup"),
    path('login/', login_page , name="login"),
    path('logout/', logout_page , name="logout"),
    path('change-profile/', change_profile , name="change_profile"),
]

App_Order/urls.py
from django.urls import path
from App_Order.views import *

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', add_to_cart , name="add"),
    path('cart/', cart_view , name="cart"),
    path('remove-cart-item/<pk>/', remove_cart , name="remove_cart"),
    path('increase-item/<pk>/', increase_cart , name="increase"),
    path('decrease-item/<pk>/', decrease_cart, name="decrease"),
    path('orders/', orders_view, name="orders_view"),
]

App_Payment/urls.py
from django.urls import path
from App_Payment.views import *

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('pay/', payment, name='payment'),
    path('status/', complete, name='complete'),
    path('purchesed/<val_id>/<tran_id>/', purchesed, name='purchesed'),
    path('remove/<pk>/', remove_coupon, name='remove_coupon'),
]

App_Shop/urls.py
from django.urls import path
from App_Shop.views import *

app_name = 'App_Shop'

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('product/<pk>/', ProductDetail, name="product_detail"),
    path('store-page/<pk>/', store_page, name="store_page"),
]

Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Auth.urls')),
    path('', include('App_Shop.urls')),
    path('orders/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('seller/', include('App_Seller.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Order/models.py
from django.db import models
from django.conf import settings

from App_Shop.models import Product

# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart')
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    coupon = models.CharField(max_length=100, default='')
    discount = models.IntegerField(default=0)
    purchased = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.quantity} X {self.item}"
    
    def get_total(self):
        total = self.quantity * self.item.price
        return format(total, '0.2f')
    
class Order(models.Model):
    orderItems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)
    
    def get_totals(self):
        total = 0
        for order_item in self.orderItems.all():
            total += float(order_item.get_total())
        return total

App_Order/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.shortcuts import get_object_or_404

from django.contrib.auth.decorators import login_required

from django.contrib import messages

from App_Order.models import *
from App_Shop.models import *

# Create your views here.
@login_required
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderItems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "Cart Item quantity was increased")
            return redirect('App_Shop:home')
        else:
            order.orderItems.add(order_item[0])
            messages.info(request, "Item added to cart")
            return redirect('App_Shop:home')
    else:
        order = Order(user=request.user)
        order.save()
        order.orderItems.add(order_item[0])
        messages.info(request, "Item added to cart")
        return redirect('App_Shop:home')
    
    
@login_required
def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchased = False)
    orders = Order.objects.filter(user=request.user, ordered = False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'App_Order/cart.html', {'order': order, 'carts':carts})
    else:
        messages.warning(request, "No item in cart")
        return redirect("App_Shop:home")
    
    


@login_required
def remove_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered = False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderItems.filter(item=item):
            order_item = Cart.objects.filter(user=request.user, item=item, purchased=False)[0]
            order_item.delete()
            order.orderItems.remove(order_item)
            messages.info(request, "Item removed successfully")
            return redirect("App_Order:cart")         
        else:
            messages.warning(request, "This item not in cart")
            return redirect("App_Shop:home")
    else:
        messages.warning(request, "You don't have any active order")
        return redirect("App_Shop:home")
    
    
@login_required
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderItems.exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity >= 1:
                order_item.quantity += 1
                order_item.save()
                messages.info(request, "Quantity was increased")
                return redirect("App_Order:cart")
        else:
            messages.warning(request, f"No '{item.name}' in your cart")
            return redirect("App_Shop:home")
    else:
        messages.warning(request, "Unable to increase")
        return redirect("App_Shop:home")
    
    
@login_required
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderItems.exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, "Quantity was decreased")
                return redirect("App_Order:cart")
            else:
                messages.warning(request, "Quantity can't be less than 1")
                return redirect("App_Order:cart")
        else:
            messages.warning(request, f"No '{item.name}' in your cart")
            return redirect("App_Shop:home")
    else:
        messages.warning(request, "Unable to decrease")
        return redirect("App_Shop:home")
    
    

@login_required
def orders_view(request):
    try:
        orders = Order.objects.filter(user=request.user, ordered=True)
        if len(orders) == 0:
            messages.warning(request, "You don't have any orders")
            return redirect("App_Shop:home")
    except:
        messages.warning(request, "You don't have any orders")
        return redirect("App_Shop:home")
        
    return render(request, 'App_Order/order.html', context={"orders": orders})

templates/App_Order/cart.html
{% extends "base.html" %} {% block style_block %} {% endblock %} {% block title_block %} Cart Items {% endblock %} {% block body_block %}
<h2>Cart Items</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Sub Total</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
    {% for item in carts %}
    <tr>
      <td><a href="{%url 'App_Shop:product_detail' pk=item.item.pk%}">{{ item.item.name }}</a></td>
      <td>{{ item.item.price }}</td>
      <td>
          <a class="btn btn-sm btn-dark" href="{%url 'App_Order:decrease' pk=item.item.pk%}">–</a>
          {{ item.quantity }}
          <a class="btn btn-sm btn-secondary" href="{%url 'App_Order:increase' pk=item.item.pk%}">+</a>
      </td>
      <td>{{ item.get_total }}</td>
      <td><a class="btn btn-danger btn-sm" href="{%url 'App_Order:remove_cart' pk=item.item.pk%}">Remove</a></td>
    </tr>
    {% endfor %}
  </tbody>
  <thead>
    <tr>
      <th scope="col" colspan="3">Total</th>
      <th scope="col" colspan="2">{{order.get_totals}}</th>
    </tr>
  </thead>
</table>
<div style="text-align: right;">
    <a href="{% url 'App_Shop:home' %}" class="btn btn-warning mr-2">Continue Shopping</a>
    <a href="{%url 'App_Payment:checkout'%}" class="btn btn-success">Check Out</a>
</div>
{% endblock %}

templates/App_Order/order.html
{% extends "base.html" %} {% block style_block %} {% endblock %} {% block title_block %} My Orders {% endblock %} {% block body_block %}
<h2>My Orders</h2>
<div class="row">
  <div class="col-md-12">
    <div class="card mt-5" style="height: auto">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Order ID</th>
              <th scope="col">Products</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            {% for order in orders %}
            <tr>
              <td>{{ order.id }}</td>
              <td>
                <ul>
                  {% for item in order.orderItems.all %}
                  <li><a href="{%url 'App_Shop:product_detail' pk=item.item.pk%}">{{ item.item.name }}</a> X {{ item.quantity }}</li>
                  {% endfor %} 
                </ul>
              </td>
              <td class="text-primary mt-3">Order on process</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="w-100 d-flex mt-4">
        <a href="{% url 'App_Shop:home' %}" class="btn btn-info m-auto">Back to home</a>
    </div>
  </div>
</div>
{% endblock %}