App_Auth/urls.py
from django.urls import path
from App_Auth.views import *

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', signup , name="signup"),
    path('login/', login_page , name="login"),
    path('logout/', logout_page , name="logout"),
    path('change-profile/', change_profile , name="change_profile"),
]

App_Order/urls.py
from django.urls import path
from App_Order.views import *

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', add_to_cart , name="add"),
    path('cart/', cart_view , name="cart"),
    path('remove-cart-item/<pk>/', remove_cart , name="remove_cart"),
    path('increase-item/<pk>/', increase_cart , name="increase"),
    path('decrease-item/<pk>/', decrease_cart, name="decrease"),
    path('orders/', orders_view, name="orders_view"),
]

App_Seller/urls.py
from django.urls import path
from App_Seller.views import *

app_name = 'App_Seller'

urlpatterns = [
    path('create-seller/', create_seller , name="create_seller"),
    path('seller-info/', fill_seller_info , name="fill_seller_info"),
    path('seller-dashboard/', seller_dashboard , name="seller_dashboard"),
    path('create-product/', create_product , name="create_product"),
    path('products/', seller_products , name="seller_products"),
    path('product-details/<pk>/', product_details , name="product_details"),
    path('edit-product/<pk>/', edit_product , name="edit_product"),
    path('delete_product/<pk>/', delete_product , name="delete_product"),
    path('create-coupon/', create_coupon , name="create_coupon"),
    path('coupons/', coupons , name="coupons"),
    path('update-coupon/<pk>/', update_coupon , name="update_coupon"),
    path('order/', order_for_seller , name="order_for_seller"),
    path('sent/<pk>/', sent , name="sent"),
    path('category-create/', create_category , name="create_category"),
    path('category/', all_category , name="all_category"),
    path('update-catgory/<pk>/', update_catgory , name="update_catgory"),
]

App_Shop/urls.py
from django.urls import path
from App_Shop.views import *

app_name = 'App_Shop'

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('product/<pk>/', ProductDetail, name="product_detail"),
    path('store-page/<pk>/', store_page, name="store_page"),
]

Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Auth.urls')),
    path('', include('App_Shop.urls')),
    path('orders/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('seller/', include('App_Seller.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load cart_tag %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <style>
      {%block style_block%}
      {% endblock %}
    </style>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>{% block title_block %} Ecommerce | ABS {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'App_Shop:home' %}">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{%url 'App_Shop:home'%}"
                >Home <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'App_Order:cart'%}">
                <i class="fa fa-shopping-cart"></i>
                Cart
                <span class="badge badge-secondary">{{request.user | cart_total}}</span>
                </a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
              {%if user.profile.full_name%}
                @{{user.profile.full_name}}
              {%else%}
              @Profile
              {%endif%}
              </a>
              <div
                class="dropdown-menu"
                aria-labelledby="navbarDropdownMenuLink"
              >
                <a
                  class="dropdown-item"
                  href="{% url 'App_Auth:change_profile' %}"
                  >Profile</a
                >
                <a class="dropdown-item" href="{%url 'App_Order:orders_view'%}">Orders</a>
                {%if user.role == 'seller'%}
                <a class="dropdown-item" href="{%url 'App_Seller:seller_dashboard'%}">Seller</a>
                {%endif%}
                <hr />
                <a class="dropdown-item" href="{% url 'App_Auth:logout' %}"
                  >Logout</a
                >
              </div>
            </li>
            {%else%}
            <li class="nav-item">
              <a class="nav-link" href="{%url 'App_Auth:login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'App_Auth:signup'%}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'App_Seller:create_seller'%}">Sign Up(Seller)</a>
            </li>
            {%endif%}
          </ul>
        </div>
      </div>
    </nav>
    {%if user.role == 'seller'%}
    <div class="side-bar" style="left: -320px;">
        <h2 style="text-align: center;"><a href="{%url 'App_Seller:seller_dashboard'%}">Dashboard</a></h2>
        <ul class="side-bar-lists">
            <li>
                <a href="{%url 'App_Seller:create_category'%}"><i class="fa-solid fa-plus"></i> Category</a>
            </li>
            <li>
                <a href="{%url 'App_Seller:create_product'%}"><i class="fa-solid fa-plus"></i>Product</a>
            </li>
            <li>
                <a href="{%url 'App_Seller:create_coupon'%}"><i class="fa-solid fa-plus"></i> Coupon</a>
            </li>
            <li>
                <a href="{%url 'App_Seller:seller_products'%}">My Products</a>
            </li>
            <li>
                <a href="{%url 'App_Seller:order_for_seller'%}">My Orders</a>
            </li>
            <li>
                <a href="{%url 'App_Seller:coupons'%}">My Coupons</a>
            </li>
            <li>
                <a href="{%url 'App_Seller:all_category'%}">Categories</a>
            </li>
            <li>
                <a href="{%url 'App_Seller:fill_seller_info'%}">Edit Seller Info</a>
            </li>
        </ul>
    </div>
    <button type="button" class="toggle-seller"><i class="fa-solid fa-bars-staggered fa-2x"></i></button>
    {%endif%}
    <div class="container p-4">
      <div class="messages container">
        {%if messages%} {%for message in messages%}
        <div
          {%if
          message.tags%}
          class="alert alert-{{message.tags}} alert-dismissible fade show"
          {%
          endif
          %}
          role="alert"
        >
          {{message}}
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {%endfor%} {%endif%}
      </div>
      {% block body_block%} {% endblock %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/index.js' %}"></script>
  </body>
</html>