App_Auth/urls.py
from django.urls import path
from App_Auth.views import *

app_name = 'App_Auth'

urlpatterns = [
    path('signup/', signup , name="signup"),
    path('login/', login_page , name="login"),
    path('logout/', logout_page , name="logout"),
    path('change-profile/', change_profile , name="change_profile"),
]

App_Payment/urls.py
from django.urls import path
from App_Payment.views import *

app_name = 'App_Payment'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('pay/', payment, name='payment'),
    path('status/', complete, name='complete'),
    path('purchesed/<val_id>/<tran_id>/', purchesed, name='purchesed'),
    path('remove/<pk>/', remove_coupon, name='remove_coupon'),
]

App_Shop/urls.py
from django.urls import path
from App_Shop.views import *

app_name = 'App_Shop'

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('product/<pk>/', ProductDetail, name="product_detail"),
    path('store-page/<pk>/', store_page, name="store_page"),
]

Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Auth.urls')),
    path('', include('App_Shop.urls')),
    path('orders/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls')),
    path('seller/', include('App_Seller.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Payment/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    address = models.CharField(max_length=264, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    city = models.CharField(max_length=30, blank=True)
    country = models.CharField(max_length=20, blank=True)
    
    def __str__(self):
        return f"{self.user.profile.full_name}'s billing address"
    
    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]
        for field_name in field_names:
            value = getattr(self, field_name)
            if value is None or value == "":
                return False
        return True
    
    class Meta:
        verbose_name_plural = 'Billing Address'
        

App_Payment/forms.py
from django import forms
from App_Payment.models import BillingAddress

class BillingAddressForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields = ('address', 'zipcode', 'city', 'country')
        

App_Payment/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

from App_Payment.forms import BillingAddressForm
from App_Payment.models import BillingAddress
from App_Order.models import Order, Cart
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from App_Seller.models import *

#payment methods
from sslcommerz_lib import SSLCOMMERZ

# Create your views here.
@login_required
def checkout(request):
    discount_total = 0
    restart_cart = Cart.objects.filter(user=request.user, purchased = False)
    for item in restart_cart:
        coupons = Coupon.objects.filter(seller=item.item.created_by)
        expired = True
        for coupon in coupons:
            if item.coupon == coupon.code:
                date_time_start = datetime.datetime.strptime(str(coupon.start_date)[:19], "%Y-%m-%d %H:%M:%S")
                date_time_end = datetime.datetime.strptime(str(coupon.expiry_date)[:19], "%Y-%m-%d %H:%M:%S")
                if coupon.active and date_time_start < datetime.datetime.now():
                    if date_time_end > datetime.datetime.now():
                        expired = False
        if expired:
            item.coupon = ""
            item.discount = 0
            item.save()
        if item.discount == 0:
            discount_total += item.quantity * item.item.price
        discount_total += item.discount
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]
    form = BillingAddressForm(instance=saved_address)
    order_qs = Order.objects.filter(user=request.user, ordered = False)
    orders = order_qs[0].orderItems.all()
    final_orders = []
    for order in orders:
        coupons = Coupon.objects.filter(seller=order.item.created_by)
        filtered_coupon = []
        for coupon in coupons:
            date_time_start = datetime.datetime.strptime(str(coupon.start_date)[:19], "%Y-%m-%d %H:%M:%S")
            date_time_end = datetime.datetime.strptime(str(coupon.expiry_date)[:19], "%Y-%m-%d %H:%M:%S")
            if coupon.active and date_time_start < datetime.datetime.now():
                if date_time_end > datetime.datetime.now():
                    filtered_coupon.append(coupon)
        final_orders.append({'order': order, 'coupon': filtered_coupon})
    order_total = order_qs[0].get_totals()
    if request.method == 'POST':
        if 'custom_form_submit' in request.POST:
            code = request.POST["code"].strip()
            cart = Cart.objects.get(id=request.POST['id'])
            coupons = Coupon.objects.filter(seller=cart.item.created_by)
            for coupon in coupons:
                if coupon.code == code:
                    cart.coupon = code
                    price = cart.item.price * cart.quantity
                    cart.discount = price - (price * coupon.discount / 100)
                    cart.save()
                    messages.success(request, "Coupon added successfully!")
                    return redirect('App_Payment:checkout')
            messages.warning(request, "Invalid Coupon!")        
            return redirect('App_Payment:checkout')
        else:
            form = BillingAddressForm(request.POST, instance=saved_address)
            if form.is_valid():
                form.save()
    return render(request, 'App_Payment/checkout.html', context={"address": saved_address,"form": form, "orders": final_orders, "total": order_total, "final_price": discount_total, "discount": order_total - discount_total})


@login_required
def remove_coupon(request, pk):
    item = Cart.objects.get(pk=pk)
    item.coupon = ""
    item.discount = 0
    item.save()
    messages.info(request, "Coupon Removed")        
    return redirect('App_Payment:checkout')


@login_required
def payment(request):
    discount_total = 0
    restart_cart = Cart.objects.filter(user=request.user, purchased = False)
    for item in restart_cart:
        coupons = Coupon.objects.filter(seller=item.item.created_by)
        expired = True
        for coupon in coupons:
            if item.coupon == coupon.code:
                date_time_start = datetime.datetime.strptime(str(coupon.start_date)[:19], "%Y-%m-%d %H:%M:%S")
                date_time_end = datetime.datetime.strptime(str(coupon.expiry_date)[:19], "%Y-%m-%d %H:%M:%S")
                if coupon.active and date_time_start < datetime.datetime.now():
                    if date_time_end > datetime.datetime.now():
                        expired = False
        if expired:
            item.coupon = ""
            item.discount = 0
            item.save()
        if item.discount == 0:
            discount_total += item.quantity * item.item.price
        discount_total += item.discount
    saved_address = BillingAddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]
    if not saved_address.is_fully_filled():
        messages.warning(request,"Complete shipping address")
        return redirect("App_Payment:checkout")
    if not request.user.profile.is_fully_filled():
        messages.warning(request,"Complete profile details first!")
        first = reverse("App_Auth:change_profile")
        next = reverse("App_Seller:seller_dashboard")
        return redirect("{}?next={}".format(first, next))
    store_id = 'abs65c269ecb8d55'
    store_pass = 'abs65c269ecb8d55@ssl'
    settings = { 'store_id': store_id, 'store_pass': store_pass, 'issandbox': True }
    sslcommez = SSLCOMMERZ(settings)
    
    url = request.build_absolute_uri(reverse('App_Payment:complete'))
    order_qs = Order.objects.filter(user=request.user, ordered = False)
    orders = order_qs[0].orderItems.all()
    order_count = order_qs[0].orderItems.count()
    order_total = discount_total
    
    post_body = {}
    post_body['total_amount'] = order_total
    post_body['currency'] = "BDT"
    post_body['tran_id'] = order_qs[0].pk
    post_body['success_url'] = url
    post_body['fail_url'] = url
    post_body['cancel_url'] = url
    post_body['emi_option'] = 0
    post_body['ship_postcode'] = saved_address.zipcode
    post_body['cus_add1'] = request.user.profile.address_1
    post_body['cus_city'] = request.user.profile.city
    post_body['cus_name'] = request.user.profile.full_name
    post_body['cus_country'] = request.user.profile.counrty
    post_body['cus_email'] = request.user.email
    post_body['cus_phone'] = request.user.profile.phone
    post_body['ship_name'] = request.user.profile.full_name
    post_body['ship_add1'] = saved_address.address
    post_body['ship_city'] = saved_address.city
    post_body['ship_country'] = saved_address.country
    post_body['shipping_method'] = "Courier"
    post_body['multi_card_name'] = "NA"
    post_body['num_of_item'] = order_count
    post_body['product_name'] = orders
    post_body['product_category'] = "Multiple Category"
    post_body['product_profile'] = "general"
    
    response = sslcommez.createSession(post_body)
    pay_url = response['GatewayPageURL']
    return redirect(pay_url)

@csrf_exempt
def complete(request):
    if request.method == 'post' or request.method == 'POST':
        payment_data = request.POST
        status = payment_data['status']
        if status == 'VALID':
            messages.success(request, "Payment successful")
            val_id = payment_data['val_id']
            tran_id = payment_data['tran_id']
            return HttpResponseRedirect(reverse('App_Payment:purchesed', kwargs={'val_id': val_id, 'tran_id': tran_id}))
        elif status == 'FAILED':
            messages.warning(request, "Payment failed! Please Try Again")
    return render(request, 'App_Payment/complete.html')


@login_required
def purchesed(request, val_id, tran_id):
    cart_items = Cart.objects.filter(user=request.user, purchased=False)
    order_qs = Order.objects.filter(user=request.user, ordered = False)    
    order = order_qs[0]
    order.ordered = True
    order.paymentId = val_id
    order.orderId = tran_id
    order.save()
    for item in cart_items:
        item.purchased = True
        item.save()
    return HttpResponseRedirect(reverse('App_Order:orders_view'))

templates/App_Payment/checkout.html
{% extends "base.html" %}
{%load crispy_forms_tags%}
{%block style_block%}
    .checkout-page{
        display: flex;
        justify-content: space-around;
        align-items: center;
        padding: 10px;
        width: 100%;
    }
    .form{
        display: flex;
        justify-content: space-around;
        flex-direction: column;
        align-items: center;
        padding: 10px;
        margin: 10px;
        flex: 3;
        box-shadow: 0px 0px 5px black;
        width: 100%;
    }
    .form form{
        width: 100%;
    }
    .items{
        flex: 2;
        padding: 10px;
        margin: 10px;
        align-self: flex-start;
        border: 1px solid black;
    }
    .list{
        box-shadow: 0px 0px 5px black;
        padding: 10px;
        margin: 10px;
        list-style: none;
    }
    @media (max-width: 768px) {
        .checkout-page{
            flex-direction: column;
        }
    }
{%endblock%}
{%block title_block%}Check Out{%endblock%}
{%block body_block%}

<h2 style="text-align: center;">Check Out</h2>
<div class="checkout-page">
    <div class="form" style="align-self: flex-start;">
        <h3>Confirm Address</h3>
        <form method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <div class="w-100 d-flex">
                <button class="btn btn-info ml-auto" type="submit">Save Address</button>
            </div>
        </form>
    </div>
    <div class="items">
        <ul>
            <h3 style="text-align:center;">Items</h3>
            {%for order in orders%}
                <li class="list">
                    <a href="{%url 'App_Shop:product_detail' pk=order.order.item.pk%}">{{order.order.item.name}}</a> X {{order.order.quantity}} = 
                    {%if order.order.discount%}
                    <span style="color: green;font-weight: bold;">{{order.order.discount}}</span>
                    <del>{{order.order.get_total}}</del>
                    {%else%}
                    <b>{{order.order.get_total}}</b>
                    {%endif%}
                    <div class="w-100 m-2 coupon-parent">
                        <p class="copy-message"></p>
                        Available Coupons:
                        {%if not order.coupon%}
                        No coupon
                        {%endif%}
                        {%for coupon in order.coupon%}
                        <span class="p-1 border coupon-code">{{coupon}}</span>
                        {%endfor%}
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <input required type='text' name="code" class="form-control" placeholder="Enter code" />
                        <input type='hidden' name="id" value="{{order.order.id}}"/>
                        <button class="btn btn-danger ml-auto btn-sm m-1" type="submit" name="custom_form_submit">Add Coupon</button>
                    </form>
                    {%if order.order.coupon%}
                    <p>Applied Coupon: <span style="cursor: default" class="btn btn-sm btn-secondary">{{order.order.coupon}}<a href="{%url 'App_Payment:remove_coupon' pk=order.order.pk%}" class="text-warning ml-2"><i class="fa-solid fa-x"></i></a></span></p>
                    {%endif%}
                </li>
            {%endfor%}
        </ul>
        <h4 style="text-align:right;">Regular Price: {{total|floatformat:2}}&#2547;</h4>
        <h4 style="text-align:right; color: green;">Discount: {{discount|floatformat:2}}&#2547;</h4>
        <h3 style="text-align:right;">Final Price: {{final_price|floatformat:2}}&#2547;</h3>
        {%if address.is_fully_filled %}
            <a href="{%url 'App_Payment:payment'%}" class="btn btn-success w-100">Make Payment</a>
        {%else %}
            <p class="alert alert-warning">Please fill all the field and save to payment</p>
        {%endif %}
    </div>
</div>

{%endblock%}

templates/App_Payment/complete.html
{% load cart_tag %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="refresh" content="5; url={%url 'App_Shop:home'%}" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <title>Payment Status</title>
  </head>
  <body>
    <div class="messages container mt-2">
        {%if messages%} {%for message in messages%}
        <div
          {%if
          message.tags%}
          class="alert alert-{{message.tags}} alert-dismissible fade show"
          {%
          endif
          %}
          role="alert"
        >
          {{message}}
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {%endfor%} {%endif%}
      </div>
      <h1 style="text-align: center; margin: 1rem;">Page will redirect autometically after 5 seconds.</h1>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>